---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-redmine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redmine
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
        - image: redmine:4.1.1
          name: redmine
          env:
            - name: REDMINE_DB_POSTGRES
              value: database
            - name: REDMINE_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: username
            - name: REDMINE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: password
            - name: REDMINE_DB_DATABASE
              value: testdatabase
            - name: REDMINE_SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: ssecretkey
          ports:
            - containerPort: 3000
              protocol: TCP