---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:10.13
          name: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: password
            - name: POSTGRES_DB
              value: testdatabase
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: pg-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pg-volume
          persistentVolumeClaim:
            claimName: postgres-pvc